name: Deploy to Surge

on:
  push:
    branches:
      - main  # O usa la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge
      run: |
        npm install --global surge
        surge --version  # Verifica que surge esté instalado

    - name: Surge login
      run: |
        surge login --token ${{ secrets.SURGE_TOKEN }}  # Login usando el token

    - name: Deploy to Surge
      run: surge --project ./ --domain ${{ secrets.SURGE_SUBDOMAIN }} --token $SURGE_TOKEN
