name: Deploy to Surge

on:
  push:
    branches:
      - main  # Puedes cambiar 'master' por 'main' si tu rama principal es 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_LOGIN: ${{ secrets.xaviercolon061@gmail.com }} # Email registrado en Surge.sh
        SURGE_TOKEN: ${{ secrets.60a133de789c437f6c466bc5a47609c0 }} # API Key generada en Surge
      run: surge --project ./ --domain ${{ secrets.miwebxavier }}.surge.sh --token $SURGE_TOKEN
