name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_EMAIL }}  # Correo registrado en Surge.sh
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # API Key generada en Surge
      run: surge --project ./ --domain ${{ secrets.SURGE_SUBDOMAIN }}.surge.sh --token $SURGE_TOKEN
