name: Deploy to Surge

on:
  push:
    branches:
      - main  # Asegúrate de usar 'main' si tu rama principal es 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge
      run: |
        npm install --global surge
        surge --version  # Verifica que surge se haya instalado correctamente

    - name: Surge login
      run: |
        surge login --token ${{ secrets.SURGE_TOKEN }}  # Login explícito usando el token

    - name: Deploy to Surge
      run: surge --project ./ --domain ${{ secrets.SURGE_SUBDOMAIN }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
